//
//  Descriptions.swift
//  AITrainer
//
//  Created by 안병욱의 mac on 2024/01/17.
//

import Foundation

struct Descriptions {
    
    static let Description: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n"
    
    static let SquatDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to leg, core, shoulder, hip and knee movements. \n\n\n"
    
    static let DeadliftDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to leg, arm, shoulder, elbow, hip and root movements. \n\n\n"
    
    static let PullupDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, shoulder, elbow, wrist and root movements. \n\n\n"
    
    static let BarbellrowDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, shoulder, elbow, wrist, hip and root movements. \n\n\n"
    
    static let ShoulderpressDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, shoulder, elbow, wrist and root movements. \n\n\n"
    
    static let OverheadpressDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, root, shoulder, elbow, wrist and root movements. \n\n\n"
    
    static let LateralraiseDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, root, shoulder, elbow and wrist movements. \n\n\n"
    
    static let InclinepressDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, shoulder, elbow, wrist and root movements. \n\n\n"
    
    static let DipsDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, root, shouder, elbow and wrist movements. \n\n\n"
    
    static let FreepostureDescription: String = " 1. The subject’s height should ideally be at least a third of the overall image height.\n\n\n 2. A large portion of the subject’s key body regions and points should be present in the image.\n\n\n 3. A subject wearing flowing or robe-like clothing reduces the detection accuracy.\n\n\n 4. Attempting to detect body poses in dense crowd scenes is likely to produce inaccurate results.\n\n\n 5. To perform more accurate exercise, exercise with the help of an expert.\n\n\n 6. Make sure that the line remains horizontal or vertical. \n\n\n 7. This exercise requires attention to arm, leg and root movements. \n\n\n"
    
}
